[general]
    entrypoint = "main"

    # AWS Polly specific
    # https://docs.aws.amazon.com/polly/latest/dg/voicelist.html
    default_tts_voice = "Astrid"
    # en-US , sv-SE
    # https://docs.aws.amazon.com/polly/latest/dg/SupportedLanguage.html
    default_tts_lang = "sv-SE"

# main
[[fn]]
    name = "main"
    prefix = { file = "files/atp-intro.mp3" }

    actions = [
        { num = 1, t = "fn", dst = "personalmenu"},
        { num = 2, t = "fn", dst = "barmenu"},
        { num = 3, t = "srv", dst = "trainmenu"},
        { num = 4, t = "fn", dst = "systemetmenu"},
        { num = 5, t = "def", dst = "uganda"},
        { num = 11, t = "fn", dst = "dee"},
    ]

# personalmenu
[[fn]]
    name = "personalmenu"
    prefix = { tts = {voice = "Astrid", msg = """Personlig service meny,
    för saldo, tryck ett, för promille, tryck två,
    för fulöls poäng, tryck tre, för att gå tillbaka, tryck 0""" }}
    exit = "main"

    actions = [
        { t = "srv", dst= "balance"},
        { t = "srv", dst= "promille"},
        { t = "srv", dst= "fulolpoints"},
    ]



# uganda
[[fn]]
    name = "uganda"
    prefix = { tts = {voice = "Mads", msg = """TRYCK, ETT, till FYRKANT, 
    NOLL FÖR ATT GÅ TILLBAKA""", lang = "da-DK"} }
    exit = "main"

    actions = [
        { t = "randomfile", dst= "./files/ugandan/"},
        { t = "file", dst = "files/ugandan/COMMANDO-COMMANDO.ogg", wait = true },
        { t = "file", dst = "files/ugandan/Commando-1.ogg", wait = true },
        { t = "file", dst = "files/ugandan/Gwe-Gwe-Gwe.ogg", wait = true },
        { t = "file", dst = "files/ugandan/One-hell-of-a-movie.ogg", wait = true },
        { t = "file", dst = "files/ugandan/WHAT-THE-FU.ogg", wait = true },
        { t = "file", dst = "files/ugandan/Tough-Commando-on-da-Mission.ogg", wait = true },
        { t = "file", dst = "files/ugandan/UGAANDA.ogg", wait = true },
        { t = "file", dst = "files/ugandan/HELLO-2.ogg", wait = true },
        { t = "file", dst = "files/ugandan/SUPA-MAFIA-ON-THE-RUN.ogg", wait = true },
        { t = "file", dst = "files/ugandan/Warrior.ogg", wait = true },
    ]
