[general]
    entrypoint = "main"
    # AWS Polly specific
    # https://docs.aws.amazon.com/polly/latest/dg/voicelist.html
    default_tts_voice = "Astrid"
    # en-US , sv-SE
    # https://docs.aws.amazon.com/polly/latest/dg/SupportedLanguage.html
    default_tts_lang = "sv-SE"

# main
[[fn]]
    name = "main"
    prefix = { file = { src = "files/atp-intro.mp3" } }
    actions = [
        { num = 1, t = "fn", dst = "personalmenu" },
        { num = 2, t = "fn", dst = "uganda" },
        { num = 3, t = "srv", srv = { dst = "traintimes", tmpl = """{{.K.InformationOwner}}, 
        {{index .K.ProductInformation 0}}, 
        {{.K.TypeOfTraffic}} nummer,  
        {{.K.TechnicalTrainIdent}}, 
        Från {{.From.AdvertisedLocationName}},  
        Till {{.To.AdvertisedLocationName}},  
        avgår från spår: {{.K.TrackAtLocation}}, 
        klockan {{.Hour}} och {{.Minute}}""", args = { station = "Reftele" } } },
        { num = 4, t = "fn", dst = "systemetmenu" },
        { num = 5, t = "def", dst = "uganda" },
        { num = 9, t = "fn", dst = "extramenu" },
    ]

# personalmenu
[[fn]]
    name = "personalmenu"
    prefix = { tts = { voice = "Astrid", msg = """Personlig service meny,
    för saldo, tryck ett, för promille, tryck två,
    för fulöls poäng, tryck tre, för att gå tillbaka, tryck 0""" } }

    actions = [
        { t = "srv", dst = "balance" },
        { t = "srv", dst = "promille" },
        { t = "srv", dst = "fulolpoints" },
    ]

# extramenu
[[fn]]
    name = "extramenu"
    prefix = { tts = { voice = "Astrid", msg = """Välkommen till extra menyn,
     för perrra, tryck ett,
     för drog slang, tryck två,
     ugandan, tryck tre,
     syra lotto, tryck fyra,
     för att gå tillbaka, tryck 0""" } }

    actions = [
        { t = "fn", dst = "perrralotto" },
        { t = "srv", srv = { dst = "drogslang", tmpl = """Har du koll på drogslangen? {{.Slang}}""" } },
        { t = "fn", dst = "ugandan" },
        { t = "fn", dst = "syralotto" },
    ]


################################
########## SOUNDBOARDS 
################################
# perrralotto
[[fn]]
    name = "perrralotto"
    prefix = { tts = { msg = """TRYCK ETT FÖR RANDOM, 
    TVÅ till FYRKANT FÖR FASTA ALTERNATIV,
    NOLL FÖR ATT GÅ TILLBAKA""" } }

    actions = [
        { t = "randomfile", randomfile = { folder = "./files/perrra/" } },
        { t = "file", file = { src = "files/perrra/are-bengt.ogg" } },
        { t = "file", file = { src = "files/perrra/avinstallera-win95.ogg" } },
        { t = "file", file = { src = "files/perrra/det-var-inte-bra.ogg" } },
        { t = "file", file = { src = "files/perrra/en-warez-dator.ogg" } },
        { t = "file", file = { src = "files/perrra/fixa-lite-skit.ogg" } },
        { t = "file", file = { src = "files/perrra/fixa-lite-warez.ogg" } },
        { t = "file", file = { src = "files/perrra/hackare-va.ogg" } },
        { t = "file", file = { src = "files/perrra/hur-ar-det-med-mircwaret.ogg" } },
        { t = "file", file = { src = "files/perrra/knarket.ogg" } },
        { t = "file", file = { src = "files/perrra/pirat-version.ogg" } },
    ]


# uganda
[[fn]]
    name = "uganda"
    prefix = { tts = { voice = "Mads", msg = """TRYCK, ETT, till FYRKANT, 
    NOLL FÖR ATT GÅ TILLBAKA""", lang = "da-DK" } }

    actions = [
        { t = "randomfile", randomfile = { folder = "./files/ugandan/" } },
        { t = "file", file = { src = "files/ugandan/Commando-1.ogg" } },
        { t = "file", file = { src = "files/ugandan/Gwe-Gwe-Gwe.ogg" } },
        { t = "file", file = { src = "files/ugandan/One-hell-of-a-movie.ogg" } },
        { t = "file", file = { src = "files/ugandan/WHAT-THE-FU.ogg" } },
        { t = "file", file = { src = "files/ugandan/Tough-Commando-on-da-Mission.ogg" } },
        { t = "file", file = { src = "files/ugandan/UGAANDA.ogg" } },
        { t = "file", file = { src = "files/ugandan/HELLO-2.ogg" } },
        { t = "file", file = { src = "files/ugandan/SUPA-MAFIA-ON-THE-RUN.ogg" } },
        { t = "file", file = { src = "files/ugandan/Warrior.ogg" } },
    ]

# syralotto
[[fn]]
    name = "syralotto"
    prefix = { tts = { msg = """TRYCK ETT FÖR RANDOM, 
    TVÅ till FYRKANT FÖR FASTA ALTERNATIV,
    NOLL FÖR ATT GÅ TILLBAKA""" } }

    actions = [
        { t = "file", file = { src = "files/lasse-liten/e.ogg" } },
        { t = "file", file = { src = "files/lasse-liten/lsd.ogg" } },
        { t = "file", file = { src = "files/lasse-liten/acid-house.ogg" } },
        { t = "file", file = { src = "files/lasse-liten/goa-trance.ogg" } },
        { t = "file", file = { src = "files/lasse-liten/electro.ogg" } },
        { t = "file", file = { src = "files/lasse-liten/garage.ogg" } },
        { t = "file", file = { src = "files/lasse-liten/deep-house.ogg" } },
        { t = "file", file = { src = "files/lasse-liten/e-type.ogg" } },
        { t = "file", file = { src = "files/lasse-liten/allt-snurrar.ogg" } },
        { t = "file", file = { src = "files/lasse-liten/torr-i-munnen.ogg" } },
        { t = "file", file = { src = "files/lasse-liten/josses-vad-det-gar-igang.ogg" } },
    ]

    # example
    # [[fn]]
    #     name = "example"
    #     prefix = { tts = {voice = "Astrid", msg = """this function
    #     has a lot of things so i can remember""", lang = "en-US" } }
    ##    this will ignore the callstack and go back to the entrypoint
    #     clear_callstack = true
    #     actions = [
    #         { t = "srv", dst= "balance"},
    #         { t = "srv", dst= "promille"},
    #         { t = "randomfile", randomfile = { folder = "./files/ugandan/" } },
    #         { t = "file", file = { src = "files/ugandan/Commando-1.ogg" } },
    #     ]
