# MCH 2022

[general]
    entrypoint = "main"
    # AWS Polly specific
    # https://docs.aws.amazon.com/polly/latest/dg/voicelist.html
    default_tts_voice = "Kendra"
    # en-US , sv-SE
    # https://docs.aws.amazon.com/polly/latest/dg/SupportedLanguage.html
    default_tts_lang = "en-US"

# main
[[fn]]
    name = "main"
    prefix = { tts = { msg = "WELCOME TO THE PHONE SYSTEM" } }
    actions = [
        # 1 ) Personlig meny
        { num = 1, queue = "customerservice" },
        { num = 9, dst = "extramenu" },
        # announce
        { num = 10, clear = true },
    ]

[[queue]]
    name = "customerservice"

    entrymsg = { tts = { msg = """Please wait while we try to connect you to one
    of our customer service representatives""" }, wait = true }
    bgmusic = { src = "files/hold.mp3" }
    currentpos = { msg = "Your current place in line is: {{.Position}}"} 
    end = { tts = { msg = "Technical error, please try again."}}

    [[queue.prompt]]
        prompt = { tts = { msg = """"We are currently experiencing high call volumes.
    Your call will be answered as soon as possible by one of our agents."""}}
        weight = 4
    
    [[queue.prompt]]
        prompt = { tts = { msg = """"You may find answers to your questions by visiting
        w w w . anderstorpsfestivalen . s e"""}}
        weight = 1

    [[queue.prompt]]
        empty = true
        weight = 3